spring:
  datasource:
   driver-class-name: org.h2.Driver
   username: h2database
   url: jdbc:h2:mem:testdb
   password: westsata
logging:
  level:
    org:
      h2: debug
      springframework:
        jdbc:
          core: debug
        orm:
          jpa: debug

